name: "test"
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: "./"

    - name: get properties
      id: json_properties
      uses: ./
      with: 
        file_path: 'package.json'

    - run: |
        echo ${{steps.json_properties.outputs.name}}
        echo ${{steps.json_properties.outputs.version}}
        
    - name: get specified property
      id: repository_type
      uses: ./
      with: 
        file_path: 'package.json'
        prop_path: 'repository.type'

    - run: |
        echo ${{steps.repository_type.outputs.value}}

